image: node:latest

stages:
  - release

publish:
  stage: release
  interruptible: false
  retry: 1
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc 
    - npm publish
  rules:
    - if: $CI_COMMIT_TAG
