image: node:20

publish:
  stage: deploy
  interruptible: false
  retry: 1
  script:
    - npm config set -- '//registry.npmjs.org/:_authToken' "${NPM_AUTH_TOKEN}"
    - npm publish
  rules:
    - if: $CI_COMMIT_TAG
