#!/usr/bin/env node

/*
  This file is part of MicroRender, a basic rendering framework.
  Copyright (C) 2023-2024 Benjamin Wilkins

  MicroRender is free software: you can redistribute it and/or modify it under the terms of the
  GNU Lesser General Public License as published by the Free Software Foundation, either version 3
  of the License, or (at your option) any later version.

  MicroRender is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
  even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public License along with MicroRender.
  If not, see <https://www.gnu.org/licenses/>.
*/

import process from "node:process";
import fs from "node:fs/promises";
import fse from "fs-extra/esm"
import path from "node:path";
import { fileURLToPath } from "node:url";

import * as esbuild from "esbuild";

const command = process.argv[2];
const cwd = process.cwd();
const microrender_dir = path.dirname(fileURLToPath(import.meta.url));
const build_dir = path.join(cwd, "build");

const serverImport = `import { init } from "${path.join(microrender_dir, "server/init.js")}";\n\n`;
const browserImport = `import { init } from "${path.join(microrender_dir, "client/init.js")}";\n\n`;

const help = `
Microrender builder

This command sets up your project to be uploaded to cloudflare
and ensures the project is bundled correctly by webpack.

Available commands:
  build: creates autogenerated files eg. _worker.js
  clean: removes autogenerated files
`

async function getFragments() {
  const fragment_dirs = new Map;
  const fragments = new Map;

  fragment_dirs.set(null, cwd);
  fragment_dirs.set("microrender", microrender_dir);

  for (const [identifier, dirname] of fragment_dirs) {
    for (const fragment of await fs.readdir(path.join(dirname, "fragments"), {withFileTypes: true})) {
      if (fragment.isDirectory()) {
        fragments.set(identifier ? `${identifier}:${fragment.name}` : fragment.name, path.join(fragment.path, fragment.name));
      };
    };
  };

  return fragments;
};

async function transformFiles(fragments) {
  await fse.emptyDir(build_dir);

  for (const [identifier, fragment] of fragments) {
    await fse.copy(path.join(fragment, "fragment.html"), path.join(build_dir, "fragments", `${identifier}.html`));
  };
};

async function addFragments(file, fragments, env, indent) {
  await file.write(`${indent ?? ""}const fragments = new Map;\n\n`);

  for (const [identifier, fragment] of fragments) {
    await file.write(`${indent ?? ""}fragments.set("${identifier}", (await import("${path.join(fragment, "fragment.js")}")).${env});\n`);
  };

  await file.write("\n");
};

async function buildJS(fragments) {
  let workerJS;
  let browserJS;

  try {
    workerJS = await fs.open(path.join(build_dir, "_worker.js"), "w");

    await workerJS.write(serverImport);
    await addFragments(workerJS, fragments, "server");
    await workerJS.write("export default init(fragments);")
  } finally {
    workerJS.close();
  };

  try {
    browserJS = await fs.open(path.join(build_dir, "_browser.js"), "w");

    await browserJS.write(browserImport);
    await browserJS.write("(async () => {\n");
    await addFragments(browserJS, fragments, "browser", "  ");
    await browserJS.write("  init(fragments);\n");
    await browserJS.write("})();");
  } finally {
    browserJS.close();
  };

  await esbuild.build({
    entryPoints: [path.join(build_dir, "_browser.js")],
    bundle: true,
    outfile: path.join(build_dir, "assets/microrender.js"),
    sourcemap: true
  });
};

async function build() {
  let fragments = await getFragments();

  await transformFiles(fragments);
  await buildJS(fragments);
};

async function clean() {
  await fse.remove(build_dir);
};

if (command == undefined | command == "help") {
  console.log(help);
} else if (command == "build") {
  build();
} else if (command == "clean") {
  clean();
} else {
  console.log(`Unrecognised command: ${command}`);
  console.log(help);
};